apiVersion: v1
kind: Service
metadata:
  name: secondapp
spec:
  ports:
  - name: "80"
    nodePort: 31024
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    example: second
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
