apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    webserver: nginx-1
  name: nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      webserver: nginx-1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        webserver: nginx-1
    spec:
      containers:
      - image: nginx:1.12
        name: nginx-1
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always