apiVersion: apps/v1
kind: Deployment
metadata:
  name: duration-app
  labels:
    app: duration
    version: v1
spec:
  selector:
    matchLabels:
      app: duration
      version: v1
  template:
    metadata:
      labels:
        app: duration
        version: v1
    spec:
      containers:
      - name: duration-container
        image: danietomiwa/duration_prediction:v1
        ports:
        - containerPort: 8000
        # # Set the APP_NAME environment variable
        # env:
        # - name: CONFIG_VAR
        #   valueFrom:
        #     configMapKeyRef:
        #       name: our-config
        #       key: name
---
apiVersion: v1
kind: Service
metadata:
  name: duration-service
spec:
  type: NodePort
  selector:
    app: duration
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000