apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: random
  labels:
    katib-metricscollector-injection: enabled
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: optimizer
        description: Training model optimizer (sdg, adam)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: pelvic/katib-job:latest
                imagePullPolicy: Never
                command:
                  - "python3"
                  - "random_job.py"
                  - "--saved_model_dir='/train/saved_model/'"
                  - "--url='https://github.com/Pelumi-Aderinto/hello-world/raw/master/data.npy'"
                  - "--lr=${trialParameters.learningRate}"
                  - "--optimizer=${trialParameters.optimizer}"
            restartPolicy: Never
