apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowers-volume
  labels:
    app: flowers-volume
spec:
  storageClassName: "standard"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi