apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netblock
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: review-6
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    - podSelector:
        matchLabels:
          app: review-6
    ports:
      - protocol: TCP
        port: 80

